// Imágenes de ingredientes para Agotados (generado, fondo transparente u2net).
export const INGREDIENTE_IMAGES: Record<string, string> = {
  "Aceite de oliva": "/assets/img/ingredientes/aceite-de-oliva.png",
  "Aceitunas": "/assets/img/ingredientes/aceitunas.png",
  "Atún": "/assets/img/ingredientes/atun.png",
  "Bacon ahumado": "/assets/img/ingredientes/bacon-ahumado.png",
  "Calamar": "/assets/img/ingredientes/calamar.png",
  "Carne de burger": "/assets/img/ingredientes/carne-de-burger.png",
  "Carrillera": "/assets/img/ingredientes/carrillera.png",
  "Cebolla crujiente": "/assets/img/ingredientes/cebolla-crujiente.png",
  "Cheddar": "/assets/img/ingredientes/cheddar.png",
  "Chorizo": "/assets/img/ingredientes/chorizo.png",
  "Guacamole": "/assets/img/ingredientes/guacamole.png",
  "Huevo hilado": "/assets/img/ingredientes/huevo-hilado.png",
  "Jamón Gran Reserva": "/assets/img/ingredientes/jamon-gran-reserva.png",
  "Jamón cocido": "/assets/img/ingredientes/jamon-cocido.png",
  "Kétchup": "/assets/img/ingredientes/ketchup.png",
  "Lechuga": "/assets/img/ingredientes/lechuga.png",
  "Lomo al ajillo": "/assets/img/ingredientes/lomo-al-ajillo.png",
  "Mantequilla": "/assets/img/ingredientes/mantequilla.png",
  "Mayonesa": "/assets/img/ingredientes/mayonesa.png",
  "Maíz": "/assets/img/ingredientes/maiz.png",
  "Mojo picón": "/assets/img/ingredientes/mojo-picon.png",
  "Mostaza": "/assets/img/ingredientes/mostaza.png",
  "Mostaza y miel": "/assets/img/ingredientes/mostaza-y-miel.png",
  "Mozzarella / Mozzamix": "/assets/img/ingredientes/mozzarella.png",
  "Nachos TexMex": "/assets/img/ingredientes/nachos-texmex.png",
  "Orégano": "/assets/img/ingredientes/oregano.png",
  "Pan burguer": "/assets/img/ingredientes/pan-burguer.png",
  "Pan clásico 100M": "/assets/img/ingredientes/pan-clasico-100m.png",
  "Pan gourmet": "/assets/img/ingredientes/pan-gourmet.png",
  "Pan perrito": "/assets/img/ingredientes/pan-perrito.png",
  "Pan piadina": "/assets/img/ingredientes/pan-piadina.png",
  "Patatas paja": "/assets/img/ingredientes/patatas-paja.png",
  "Pepperoni": "/assets/img/ingredientes/pepperoni.png",
  "Picatostes": "/assets/img/ingredientes/picatostes.png",
  "Pintxo donostiarra": "/assets/img/ingredientes/pintxo-donostiarra.png",
  "Pollo": "/assets/img/ingredientes/pollo.png",
  "Pollo Kebab": "/assets/img/ingredientes/pollo-kebab.png",
  "Pulled pork": "/assets/img/ingredientes/pulled-pork.png",
  "Queso gorgonzola": "/assets/img/ingredientes/queso-gorgonzola.png",
  "Queso madurado": "/assets/img/ingredientes/queso-madurado.png",
  "Salchicha / Hot dog": "/assets/img/ingredientes/salchicha.png",
  "Salmón ahumado": "/assets/img/ingredientes/salmon-ahumado.png",
  "Salsa 100M": "/assets/img/ingredientes/salsa-100m.png",
  "Salsa BBQ": "/assets/img/ingredientes/salsa-bbq.png",
  "Salsa alioli": "/assets/img/ingredientes/salsa-alioli.png",
  "Salsa brava": "/assets/img/ingredientes/salsa-brava.png",
  "Salsa pomodoro / pizza": "/assets/img/ingredientes/salsa-pomodoro.png",
  "Tomate": "/assets/img/ingredientes/tomate.png",
  "Torreznos": "/assets/img/ingredientes/torreznos.png",
  "Tortilla de patatas": "/assets/img/ingredientes/tortilla-de-patatas.png",
};
