/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AppPresupuestosRouteImport } from './routes/_app/presupuestos'
import { Route as AppPagosRouteImport } from './routes/_app/pagos'
import { Route as AppOnboardingRouteImport } from './routes/_app/onboarding'
import { Route as AppFacturasRouteImport } from './routes/_app/facturas'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppConsentimientosRouteImport } from './routes/_app/consentimientos'
import { Route as AppConfiguracionRouteImport } from './routes/_app/configuracion'
import { Route as AppCalendarioRouteImport } from './routes/_app/calendario'
import { Route as AppPacientesIndexRouteImport } from './routes/_app/pacientes.index'
import { Route as AppPacientesIdRouteImport } from './routes/_app/pacientes.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const AppPresupuestosRoute = AppPresupuestosRouteImport.update({
  id: '/presupuestos',
  path: '/presupuestos',
  getParentRoute: () => AppRoute,
} as any)
const AppPagosRoute = AppPagosRouteImport.update({
  id: '/pagos',
  path: '/pagos',
  getParentRoute: () => AppRoute,
} as any)
const AppOnboardingRoute = AppOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AppRoute,
} as any)
const AppFacturasRoute = AppFacturasRouteImport.update({
  id: '/facturas',
  path: '/facturas',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppConsentimientosRoute = AppConsentimientosRouteImport.update({
  id: '/consentimientos',
  path: '/consentimientos',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracionRoute = AppConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarioRoute = AppCalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => AppRoute,
} as any)
const AppPacientesIndexRoute = AppPacientesIndexRouteImport.update({
  id: '/pacientes/',
  path: '/pacientes/',
  getParentRoute: () => AppRoute,
} as any)
const AppPacientesIdRoute = AppPacientesIdRouteImport.update({
  id: '/pacientes/$id',
  path: '/pacientes/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/calendario': typeof AppCalendarioRoute
  '/configuracion': typeof AppConfiguracionRoute
  '/consentimientos': typeof AppConsentimientosRoute
  '/dashboard': typeof AppDashboardRoute
  '/facturas': typeof AppFacturasRoute
  '/onboarding': typeof AppOnboardingRoute
  '/pagos': typeof AppPagosRoute
  '/presupuestos': typeof AppPresupuestosRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/': typeof AuthIndexRoute
  '/pacientes/$id': typeof AppPacientesIdRoute
  '/pacientes/': typeof AppPacientesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendario': typeof AppCalendarioRoute
  '/configuracion': typeof AppConfiguracionRoute
  '/consentimientos': typeof AppConsentimientosRoute
  '/dashboard': typeof AppDashboardRoute
  '/facturas': typeof AppFacturasRoute
  '/onboarding': typeof AppOnboardingRoute
  '/pagos': typeof AppPagosRoute
  '/presupuestos': typeof AppPresupuestosRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth': typeof AuthIndexRoute
  '/pacientes/$id': typeof AppPacientesIdRoute
  '/pacientes': typeof AppPacientesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/_app/calendario': typeof AppCalendarioRoute
  '/_app/configuracion': typeof AppConfiguracionRoute
  '/_app/consentimientos': typeof AppConsentimientosRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/facturas': typeof AppFacturasRoute
  '/_app/onboarding': typeof AppOnboardingRoute
  '/_app/pagos': typeof AppPagosRoute
  '/_app/presupuestos': typeof AppPresupuestosRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/': typeof AuthIndexRoute
  '/_app/pacientes/$id': typeof AppPacientesIdRoute
  '/_app/pacientes/': typeof AppPacientesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/calendario'
    | '/configuracion'
    | '/consentimientos'
    | '/dashboard'
    | '/facturas'
    | '/onboarding'
    | '/pagos'
    | '/presupuestos'
    | '/auth/callback'
    | '/auth/'
    | '/pacientes/$id'
    | '/pacientes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendario'
    | '/configuracion'
    | '/consentimientos'
    | '/dashboard'
    | '/facturas'
    | '/onboarding'
    | '/pagos'
    | '/presupuestos'
    | '/auth/callback'
    | '/auth'
    | '/pacientes/$id'
    | '/pacientes'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/_app/calendario'
    | '/_app/configuracion'
    | '/_app/consentimientos'
    | '/_app/dashboard'
    | '/_app/facturas'
    | '/_app/onboarding'
    | '/_app/pagos'
    | '/_app/presupuestos'
    | '/auth/callback'
    | '/auth/'
    | '/_app/pacientes/$id'
    | '/_app/pacientes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/presupuestos': {
      id: '/_app/presupuestos'
      path: '/presupuestos'
      fullPath: '/presupuestos'
      preLoaderRoute: typeof AppPresupuestosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pagos': {
      id: '/_app/pagos'
      path: '/pagos'
      fullPath: '/pagos'
      preLoaderRoute: typeof AppPagosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/onboarding': {
      id: '/_app/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AppOnboardingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/facturas': {
      id: '/_app/facturas'
      path: '/facturas'
      fullPath: '/facturas'
      preLoaderRoute: typeof AppFacturasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/consentimientos': {
      id: '/_app/consentimientos'
      path: '/consentimientos'
      fullPath: '/consentimientos'
      preLoaderRoute: typeof AppConsentimientosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/configuracion': {
      id: '/_app/configuracion'
      path: '/configuracion'
      fullPath: '/configuracion'
      preLoaderRoute: typeof AppConfiguracionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/calendario': {
      id: '/_app/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof AppCalendarioRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pacientes/': {
      id: '/_app/pacientes/'
      path: '/pacientes'
      fullPath: '/pacientes/'
      preLoaderRoute: typeof AppPacientesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pacientes/$id': {
      id: '/_app/pacientes/$id'
      path: '/pacientes/$id'
      fullPath: '/pacientes/$id'
      preLoaderRoute: typeof AppPacientesIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCalendarioRoute: typeof AppCalendarioRoute
  AppConfiguracionRoute: typeof AppConfiguracionRoute
  AppConsentimientosRoute: typeof AppConsentimientosRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppFacturasRoute: typeof AppFacturasRoute
  AppOnboardingRoute: typeof AppOnboardingRoute
  AppPagosRoute: typeof AppPagosRoute
  AppPresupuestosRoute: typeof AppPresupuestosRoute
  AppPacientesIdRoute: typeof AppPacientesIdRoute
  AppPacientesIndexRoute: typeof AppPacientesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCalendarioRoute: AppCalendarioRoute,
  AppConfiguracionRoute: AppConfiguracionRoute,
  AppConsentimientosRoute: AppConsentimientosRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppFacturasRoute: AppFacturasRoute,
  AppOnboardingRoute: AppOnboardingRoute,
  AppPagosRoute: AppPagosRoute,
  AppPresupuestosRoute: AppPresupuestosRoute,
  AppPacientesIdRoute: AppPacientesIdRoute,
  AppPacientesIndexRoute: AppPacientesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
